accounts/urls.py
from django.urls import path
from .views import (ContactListView, ContactAddView, ContactUpdateView,
                    ContactDeleteView)

urlpatterns = [
    path('contact/list/', ContactListView.as_view(), name='contact-list'),
    path('contact/add/', ContactAddView.as_view(), name='contact-add'),
    path('contact/<int:pk>/', ContactUpdateView.as_view(),
         name='contact-update'),
    path('contact/<int:pk>/delete/', ContactDeleteView.as_view(),
         name='contact-delete'),
]

doge_bank/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('accounts/', include(('accounts.urls', 'accounts'),
                              namespace='accounts')),
    path('admin/', admin.site.urls),
    path('auth/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('social/', include('social_django.urls', namespace='social')),
]

accounts/models.py
from django.conf import settings
from django.db import models
from localflavor.generic.models import IBANField


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    iban = IBANField(help_text='International Bank Account Number')
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

accounts/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin)
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.views.generic.edit import UpdateView, DeleteView

from .models import Contact


class ContactListView(LoginRequiredMixin, ListView):
    model = Contact


class ContactAddView(LoginRequiredMixin, CreateView):
    template_name_suffix = '_add'
    model = Contact
    fields = ['first_name', 'last_name', 'iban']
    success_url = reverse_lazy('accounts:contact-list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ContactUpdateView(LoginRequiredMixin, PermissionRequiredMixin,
                        UpdateView):
    template_name_suffix = '_update'
    model = Contact
    fields = ['first_name', 'last_name', 'iban']
    success_url = reverse_lazy('accounts:contact-list')

    def has_permission(self):
        try:
            contact = Contact.objects.get(pk=self.kwargs['pk'])
        except Contact.DoesNotExist:
            # 404 will be raised at other layer
            return True
        else:
            if contact.created_by == self.request.user:
                return True
            else:
                return False


class ContactDeleteView(LoginRequiredMixin, PermissionRequiredMixin,
                        DeleteView):
    model = Contact
    success_url = reverse_lazy('accounts:contact-list')

    def has_permission(self):
        try:
            contact = Contact.objects.get(pk=self.kwargs['pk'])
        except Contact.DoesNotExist:
            # 404 will be raised at other layer
            return True
        else:
            if contact.created_by == self.request.user:
                return True
            else:
                return False

doge_bank/views.py
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(
                reverse(settings.LOGIN_REDIRECT_URL))
        return super().dispatch(*args, **kwargs)

accounts/templates/accounts/contact_add.html
{% extends "base.html" %}
{% load static %}

{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'accounts:contact-list' %}">Contacts</a>
    &rsaquo; Contact add
</div>
{% endblock %}

{% block content %}
<h1>Add Contact</h1>

<div id="content-main">
    <form method="post">
        {% csrf_token %}
        <div class="module">
            <table>
                {{ form.as_table }}
            </table>
        </div>
        <div class="submit-row">
            <p class="deletelink-box">
                <a href="{% url 'accounts:contact-list' %}" class="closelink">Cancel</a>
            </p>
            <input type="submit" value="Save">
        </div>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/contact_confirm_delete.html
{% extends "base.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'accounts:contact-list' %}">Contacts</a>
    &rsaquo; Contact delete
</div>
{% endblock %}

{% block content %}
<h1>Delete Contact</h1>

<div id="content-main">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/contact_list.html
{% extends "base.html" %}
{% load static %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}">
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'accounts:contact-list' %}">Contacts</a>
</div>
{% endblock %}

{% block content %}
<h1>Contacts</h1>

<div id="content-main">
    <ul class="object-tools">
      <li>
        <a href="{% url 'accounts:contact-add' %}" class="addlink">Add contact</a>
      </li>
    </ul>

    <div class="module" id="changelist">
        <div class="results">
            <table id="result_list">
                <thead>
                    <tr>
                        <th scope="col" class="column-first_name">
                           <div class="text"><span>First name</span></div>
                           <div class="clear"></div>
                        </th>
                        <th scope="col" class="column-last_name">
                           <div class="text"><span>Last name</span></div>
                           <div class="clear"></div>
                        </th>
                        <th scope="col" class="column-iban">
                           <div class="text"><span>IBAN</span></div>
                           <div class="clear"></div>
                        </th>
                        <th scope="col" class="column-edit_delete">
                           <div class="clear"></div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for contact in object_list %}
                    <tr class="{% cycle 'row1' 'row2' %}">
                        <td class="field-first_name">{{ contact.first_name }}</td>
                        <td class="field-last_name">{{ contact.last_name }}</td>
                        <td class="field-iban">{{ contact.iban }}</td>
                        <th class="edit_delete">
                            {% if request.user == contact.created_by %}
                            <a href="{% url 'accounts:contact-update' contact.pk %}">Update / Delete</a>
                            {% endif %}
                        </th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/contact_update.html
{% extends "base.html" %}
{% load static %}

{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'accounts:contact-list' %}">Contacts</a>
    &rsaquo; Contact update
</div>
{% endblock %}

{% block content %}
<h1>Update Contact</h1>

<div id="content-main">
    <form method="post">
        {% csrf_token %}
        <div class="module">
            <table>
                {{ form.as_table }}
            </table>
        </div>
        <div class="submit-row">
            <p class="deletelink-box">
                <a href="{% url 'accounts:contact-delete' object.pk %}" class="deletelink">Delete</a>
            </p>
            <input type="submit" value="Save">
        </div>
    </form>
</div>
{% endblock %}

templates/base.html
{% extends "admin/base.html" %}

{% block title %}Doge Bank administration{% endblock %}

{% block usertools %}
<div id="user-tools">
    {% block welcome-msg %}
        {% if user.is_authenticated %}
            Hi <strong>{% firstof user.get_short_name user.get_username %}</strong>.
        {% endif %}
    {% endblock %}
    {% block userlinks %}
        {% if user.is_authenticated %}
            <a href="{% url "logout" %}">log out</a>
        {% endif %}
    {% endblock %}
</div>
{% endblock %}

{% block branding %}
<h1 id="site-name">
    <img src="https://s3.amazonaws.com/menda/other/doge_bank_logo.png" style="height: 50px; padding-right: 5px" />
    <a href="{% url 'index' %}">Doge Bank administration</a></h1>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'index' %}">Home</a>
</div>
{% endblock %}

{% block content %}
<a href="{% url "social:begin" "google-oauth2" %}" style="color: #fff; weight: bold">
    <div style="background-color: #4285f4; border: #4285f4 1px solid; display: block; float: left;">
        <div style="display: inline-block; padding: 10px 10px 8px 10px; background-color: #fff;">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 48 48">
                <g>
                    <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
                    <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
                    <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
                    <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
                    <path fill="none" d="M0 0h48v48H0z"></path>
                </g>
            </svg>
        </div>
        <div style="display: inline-block; padding: 0 10px; background-color: #4285f4;">
            <span style="vertical-align: 3px">Sign in with Google</span>
        </div>
    </div>
</a>
{% endblock %}